"""Generate control/include/lqr_coeffs.hpp from the offline model."""

import argparse
from pathlib import Path

from dynamics import INPUT_NAMES, STATE_NAMES
from fit_lqr import fit_gain_surface
from leg_data import (
    L_MAX,
    L_MIN,
    L_STEP,
    MODEL,
    Q_DIAG,
    R_DIAG,
)


def format_float(value: float) -> str:
    if abs(value) < 5.0e-13:
        value = 0.0
    return f"{value:.9e}f"


def render_header() -> tuple[str, object]:
    result = fit_gain_surface()

    lines = [
        "#pragma once",
        "",
        "// Generated by parallel_leg_lqr/generate_lqr_header.py.",
        "// Do not edit this table manually.",
        "//",
        "// IMPORTANT: equivalent leg COM/inertia currently use the approximation",
        "// configured in leg_data.py. Replace it with parallel-leg CAD/identified",
        "// properties before using this gain table on hardware.",
        "//",
        "// Runtime convention: u = K * (observed - reference).",
        f"// Grid: [{L_MIN:.3f}, {L_MAX:.3f}] m, step {L_STEP:.3f} m.",
        f"// Samples: {result.sample_count}.",
        f"// Fit max abs error: {result.max_abs_error:.9g}.",
        f"// Fit RMS error: {result.rms_error:.9g}.",
        f"// Worst exact-grid closed-loop max real eigenvalue: "
        f"{result.worst_closed_loop_real_part:.9g}.",
        "",
        "namespace wbr",
        "{",
        "",
        "inline constexpr float k_lqr_coefficients[40][6] =",
        "{",
    ]

    for input_index, input_name in enumerate(INPUT_NAMES):
        for state_index, state_name in enumerate(STATE_NAMES):
            row = input_index * len(STATE_NAMES) + state_index
            values = ", ".join(format_float(value) for value in result.coefficients[row])
            lines.append(
                f"    {{{values}}}, // {input_name} <- {state_name}"
            )

    lines.extend(
        [
            "};",
            "",
            f"inline constexpr float k_lqr_fit_max_abs_error = "
            f"{format_float(result.max_abs_error)};",
            f"inline constexpr float k_lqr_fit_rms_error = "
            f"{format_float(result.rms_error)};",
            "",
            "} // namespace wbr",
            "",
        ]
    )
    return "\n".join(lines), result


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    header, result = render_header()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    temporary = args.output.with_suffix(args.output.suffix + ".tmp")
    temporary.write_text(header, encoding="utf-8")
    temporary.replace(args.output)

    print(f"generated: {args.output}")
    print(f"samples: {result.sample_count}")
    print(f"max abs fit error: {result.max_abs_error:.9g}")
    print(f"RMS fit error: {result.rms_error:.9g}")
    print(
        "worst exact-grid closed-loop max real eigenvalue: "
        f"{result.worst_closed_loop_real_part:.9g}"
    )


if __name__ == "__main__":
    main()
